version: '3.8'

services:
  app:
    build:
      context: node_app
    container_name: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: node main.js
    networks:
      - network_node
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0 --init-file /docker-entrypoint-initdb.d/init.sql 
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql_files/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network_node
  nginx_proxy:
    image: nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - network_node
    ports:
      - "8080:80"
    depends_on:
      - app
networks:
  network_node:
    driver: bridge
