version: '3'

services:
  app:
    build:
      context: node_app
    container_name: node_app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: node main.js
    volumes:
      - ./node_app:/app
    networks:
      - network_node
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    # habilita acesso tty ao container
    tty: true
      #copia conteudo do container para pasta do host
      ##vamos fazer bkp dos dados do banco mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
        #      - MYSQL_USER=root
    # networks_mode:pq nao networks?
    networks:
      - network_node
  nginx_proxy:
    image: nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - network_node
    ports:
      - "8080:80"
    depends_on:
      - app
networks:
  network_node:
    driver: bridge
